### ISSUE TITLE
Catalogue Editor

### ISSUE THREAD

**Issue by riecenaidoo** [riecenaidoo/simple-soundboard#26]
## Features

- [ ] add, remove & rename Groups, Playlists
- [ ] add & remove Songs from Playlists
- [ ] remove duplicate Songs from Playlists
- [ ] persist changes between sessions

## Tasks

- [x] #48
    - need to be able to 'roll' back changes, such as removing a group, etc. without needing to reload the catalogue from file/memory.
- [x] #50
    - fix issues with data model implementation, i.e. the ability to roll back **specific** changes.
- [x] #51 
- [x] #61 
- [ ] #63 
- [ ] #62

**Comment by riecenaidoo** [comment]
GUIs

- [ ] modify Groups (add, remove, modify names)
- [ ] modify Playlists (^)
- [x] modify Playlist Songs
